source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'ember-cli-rails'
gem 'devise'
gem 'active_model_serializers'
gem 'bourbon'
gem 'neat'


group :development, :test do
  gem 'sqlite3'
end

